### ISSUE TITLE
DTW object is not subscriptable

### ISSUE THREAD

**Issue by ahmad7bashir** [esaraci/knocking#2]
Hi E. Saraci
am receiving the following error while running the code 
 
TypeError: 'DTW' object is not subscriptable

**Comment by esaraci** [comment]
Hi,

thank you for you message. Unfortunately I am not able to reproduce the error you are reporting. 

The ideal setup for the script is python==3.6.x and dtw==1.3.x, but it also works with python==3.7.4 and dtw==1.4.0. However, I suggest you to stick with dtw==1.3.x as dtw==1.4.0 might produce different results (refer to: https://github.com/pierre-rouanet/dtw/issues/44)

Make sure that you have installed the right dtw module, i.e. this one (https://pypi.org/project/dtw).

Also, if you are only interested in the results of the `clustering.py` script, you do not need to execute it at all, as all the results are uploaded in the `dataset/` folder (https://github.com/esaraci/knocking/tree/master/datasets).

**Comment by ahmad7bashir** [comment]
downgrading to dwt==1.4 does solved the problem.

thank you very much, happiness, health and wealth be with you wherever you are
peace.
